# Generated by Django 4.1.4 on 2022-12-15 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('middle_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=6)),
                ('student_class', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.school')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('relationship', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('NIN', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('academic_session', models.DateField()),
                ('status', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
